os: Visual Studio 2017
platform:
  - x64
  - x86
configuration:
  - Release
matrix:
  fast_finish: true

environment:
  # Prebuild S3 keys
  AWS_ACCESS_KEY_ID:
    secure: fA8ogg68+lo8W2gqdyINqRWGCRmpnXuP7ZhqxALG38I=
  AWS_SECRET_ACCESS_KEY:
    secure: jepVHzuEjGj5OSmBYDBBC/fj7fp2DhkBob7rHLvPKza4CyZUGP7y6WxO/6XLO0e7
  matrix:
    - nodejs_version: 10
    - nodejs_version: 11
    - nodejs_version: 12
    - nodejs_version: 13
    - nodejs_version: 14
    - nodejs_version: 15
    - nodejs_version: 16

install:
  - .\scripts\winci.bat

build: OFF
test: OFF
deploy: OFF
