name: Github packages publish

on: workflow_dispatch

jobs:
  publish:

    runs-on: [ ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest ]

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npx node-pre-gyp configure
    - run: npx node-pre-gyp build
    - run: npm test
    - run: npx node-pre-gyp package
    - run: npx node-pre-gyp-github publish
