# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bundled_gdal:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
        platforms: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp build -j max
    - name: Run unit tests
      run: npm test


  bundled_gdal_coverage:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 14.x ]
        platforms: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure --debug
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp build -j max --debug
    - name: Run unit tests
      run: npm test
    - run: npm run gcov
    - run: npm run codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  shared_gdal:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
        platforms: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get update
    - run: sudo apt-get install libgdal-dev
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure --shared_gdal
    - name: Build from sources
      run: npx @mapbox/node-pre-gyp rebuild --shared_gdal -j max
    - name: Run unit tests
      run: npm test
