name: Test published packages

on: [ release, workflow_dispatch ]

jobs:
  bundled_gdal:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
        platforms: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp install
    - run: npm test


  shared_gdal:

    runs-on: ${{ matrix.platforms }}
    
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x, 15.x ]
        platforms: [ ubuntu-16.04, ubuntu-18.04, ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get update
    - run: sudo apt-get install libgdal-dev
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure --shared_gdal
    - run: npx @mapbox/node-pre-gyp build -j max --shared_gdal
    - run: npm test
